(global-set-key (kbd "C-<tab>") #'evil-switch-to-windows-last-buffer)
(evil-global-set-key 'motion (kbd "K") 'eldoc-doc-buffer)
(evil-global-set-key 'motion (kbd "\"") 'eldoc-box-quit-frame)
(global-set-key (kbd "C-a") #'project-find-file)
;; (global-set-key (kbd "C-o") #'eshell)
