(setq user-emacs-directory "~/.config/emax")
(add-to-list 'load-path (expand-file-name "packages/evil" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/compat" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/vertico" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/corfu" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/ef-themes" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/fontaine" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/eldoc-box" user-emacs-directory))
(require 'evil)
(require 'compat)
(require 'vertico)
(require 'corfu)
(require 'ef-themes)
(require 'fontaine)
(require 'eldoc-box)
(require 'project)
(evil-mode)
(vertico-mode)
(corfu-mode)
(global-corfu-mode)
(load (expand-file-name "init.el" user-emacs-directory))
(mapc 'load (file-expand-wildcards (format "%s/modules/*.el" user-emacs-directory)))
